### ISSUE TITLE
I created this too

### ISSUE THREAD

**Issue by TomHAnderson** [hrevert/HtUserRegistrationDoctrineORM#2]
Hi,

I wanted to use HtUserRegistration and I didn't find this Doctrine module so I wrote my own.  My strategy is modeled after `zfcampus/zf-oauth2-doctrine` with configurable Doctrine connection and dynamic joins.  My first release:

https://github.com/Apigility-Skeletons/ht-user-registration-doctrine-orm/releases/tag/0.1.0

As I only found this repo after I created it I thought we could put the best of both together.  Please take a look and let me know,

Tom

**Comment by ojhaujjwal** [comment]
Thanks for creating the issue. I will look at it.
